CREATE TABLE PRICE_HISTORY (
    id      SERIAL PRIMARY KEY,
    before  BIGINT NOT NULL,
    after   BIGINT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    post_id int NOT NULL REFERENCES post (id)
);